version: '3.9'

services:
  # frontend:
  #   image: antoniopapa1991/frontend
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - backend
  backend:
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - db 
  postgres:
    container_name: nest-admin
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-admin
      PGDATA: data/postgres
    volumes:
      - ./data/pg:/data/postgres